sudo: required
services:
  - docker

before_install: 
  - docker build -t khaledkhawajki/react-test -f ./frontend/Dockerfile.dev ./frontend

scripts:
  - docker run -e CI=true khaledkhawajki/react-test npm test -- --coverage

after_success: 
  - docker build -t khaledkhawajki/asr-client ./frontend
  - docker build -t khaledkhawajki/asr-nginx ./nginx
  - docker build -t khaledkhawajki/asr-server ./backend
  # Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push khaledkhawajki/asr-client
  - docker push khaledkhawajki/asr-nginx
  - docker push khaledkhawajki/asr-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: whisper-fastapi
  env: Whisper-fastapi-env-2
  bucket_name: elasticbeanstalk-us-east-1-767397778998
  bucket_path: whisper-fastapi-bucket-path
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

env:
  global:
    - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    - AWS_SECRET_KEY=$AWS_SECRET_KEY
    - AWS_SDK_LOAD_CONFIG=1