sudo: required
services:
  - docker

before_install: 
  - docker build -t khaledkhawajki/react-test -f ./frontend/Dockerfile.dev ./frontend

scripts:
  - docker run -e CI=true khaledkhawajki/react-test npm test -- --coverage

after_success: 
  - docker build -t khaledkhawajki/asr-client ./frontend
  - docker build -t khaledkhawajki/asr-nginx ./nginx
  - docker build -t khaledkhawajki/asr-server ./backend
  # Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push khaledkhawajki/asr-client
  - docker push khaledkhawajki/asr-nginx
  - docker push khaledkhawajki/asr-server