sudo: required
services:
  - docker

before_install: 
  - docker build -t khaledkhawajki/react-test -f ./frontend/Dockerfile.dev ./frontend

scripts:
  - docker run khaledkhawajki/react-test npm test -- --coverage

after_success: 
  - docker build -t khaledkhawajki/asr-client ./frontend
  - docker build -t khaledkhawajki/asr-nginx ./nginx
  - docker build -t khaledkhawajki/asr-server ./backend