version: '3'

services:
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'

  client:
    build:
      context: ./frontend
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
